### ISSUE TITLE
"--confirm" option does not work as expected with `sys.download`

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/gptscript#176]
gptscript version - `v0.0.0-dev-8d564a58-dirty`
**Steps to reproduce the problem:**
1. Run the following script which creates a file multiple times -  `gptscript --cache=false --confirm test.gpt`

```
Tools:  github.com/gptscript-ai/vision,  github.com/gptscript-ai/image-generation , sys.write, sys.read, sys.download

1. Generate an image of a cow grazing in the open green meadows and return only the url of the image.
3. Download the url of the image generated in step 1 and write to a file cownew.png.
4. Describe the image at cow.png in the style of a Wes Anderson character.
```

2. Second time this gptscript is run , I am not prompted to override the files and the file just gets overwritten.

**Expected behavior:**
we expect the user to be presented with a confirmation message before the script tries to override the existing file.

Note - I saw the confirm option show up just once and in this case gptscript failed with following error: 

```
13:03:33 sent     [sys.write(3)]
13:03:33 sent     [sys.download(4)]
? Overwrite: cow.png (y/N) 13:03:34 ended    [sys.download(4)]
? Overwrite: cow.png Yes
13:06:05 ended    [sys.write(3)]
13:06:05 continue [main]
13:06:05 sent     [main]
         content  [1] content | Waiting for model response...
         content  [1] content | tool call vision -> {"images":"file://cow.png/","prompt":"Describe this image in the style of a Wes Anderson character."}
13:06:09 started  [vision(5)] [input={"images":"file://cow.png/","prompt":"Describe this image in the style of a Wes Anderson character."}]
13:06:09 sent     [vision(5)]
file:///Users/sangeethahariharan/Library/Caches/gptscript/repos/fb6ec1f02801c68bc1c934e3e70e66c33fe72655/node21/index.js:89
      const mime = (await fileTypeFromBuffer(data)).mime
                                                    ^

TypeError: Cannot read properties of undefined (reading 'mime')
    at resolveImageURL (file:///Users/sangeethahariharan/Library/Caches/gptscript/repos/fb6ec1f02801c68bc1c934e3e70e66c33fe72655/node21/index.js:89:53)
    at async Command.run (file:///Users/sangeethahariharan/Library/Caches/gptscript/repos/fb6ec1f02801c68bc1c934e3e70e66c33fe72655/node21/index.js:57:14)
    at async Command.parseAsync (/Users/sangeethahariharan/Library/Caches/gptscript/repos/fb6ec1f02801c68bc1c934e3e70e66c33fe72655/node21/node_modules/commander/lib/command.js:935:5)
    at async main (file:///Users/sangeethahariharan/Library/Caches/gptscript/repos/fb6ec1f02801c68bc1c934e3e70e66c33fe72655/node21/index.js:47:3)

Node.js v21.7.0
13:06:09 failed to run tool [vision] cmd [/usr/bin/env node /Users/sangeethahariharan/Library/Caches/gptscript/repos/fb6ec1f02801c68bc1c934e3e70e66c33fe72655/node21/index.js Describe this image in the style of a Wes Anderson character. file://cow.png/]: exit status 1
2024/03/22 13:06:09 ERROR: file:///Users/sangeethahariharan/Library/Caches/gptscript/repos/fb6ec1f02801c68bc1c934e3e70e66c33fe72655/node21/index.js:89
      const mime = (await fileTypeFromBuffer(data)).mime
                                                    ^

TypeError: Cannot read properties of undefined (reading 'mime')
    at resolveImageURL (file:///Users/sangeethahariharan/Library/Caches/gptscript/repos/fb6ec1f02801c68bc1c934e3e70e66c33fe72655/node21/index.js:89:53)
    at async Command.run (file:///Users/sangeethahariharan/Library/Caches/gptscript/repos/fb6ec1f02801c68bc1c934e3e70e66c33fe72655/node21/index.js:57:14)
    at async Command.parseAsync (/Users/sangeethahariharan/Library/Caches/gptscript/repos/fb6ec1f02801c68bc1c934e3e70e66c33fe72655/node21/node_modules/commander/lib/command.js:935:5)
    at async main (file:///Users/sangeethahariharan/Library/Caches/gptscript/repos/fb6ec1f02801c68bc1c934e3e70e66c33fe72655/node21/index.js:47:3)

Node.js v21.7.0
: exit status 1
```

**Comment by cjellick** [comment]
Did we ever get to the bottom of this? I havent seen anything that stated the is behahvior is actually expected. i think the current behavior is fine.

**Comment by sangee2004** [comment]
Tested with gptscript version - `v0.9.2+0f32a9d8`
"--confirm" option works as expected .

We are prompted by `sys.download`  when files already exists .

```
gptscript --confirm testconfirm.gpt 
14:17:20 started  [main]
14:17:20 sent     [main]
14:17:20 started  [image-generation(2)] [input={"prompt":"cow grazing in the open green meadows"}]
? Description: Generates images based on the specified parameters and returns a list of URLs to the generated images.
  Interpreter: /usr/bin/env python3 ${GPTSCRIPT_TOOL_DIR}/cli.py --prompt="${prompt}" --size="${size}" --quality="${quality}" --number="${number}"
  Source: github.com/gptscript-ai/image-generation/tool.gpt
  Input: {"prompt":"cow grazing in the open green meadows"}
Allow the above tool to execute? Yes
14:17:21 sent     [image-generation(2)]
         content  [2] content | ['https://oaidalleapiprodscus.blob.core.windows.net/private/org-UZ21HIS1j93qUiZVWBOGePHu/user-nfhF7k ...
         content  [2] content | 
14:17:33 ended    [image-generation(2)] [output=['https://oaidalleapiprodscus.blob.core.windows.net/private/org-UZ21HIS1j93qUiZVWBOGePHu/user-nfhF7k...]
14:17:33 continue [main]
14:17:34 sent     [main]
         content  [1] content | Waiting for model response...
         content  [1] content | <tool call> download -> {"location":"cownew.png","url":"https://oaidalleapiprodscus.blob.core.windows.net/private/org-UZ21HIS1j93qUiZVWBOGePHu/user-nfhF7kaasrYgX69n1He52KF9/img-O14wUVsuS2brJ1exDIZp4Rq1.png?st=2024-07-08T20%3A17%3A33Z&se=2024-07-08T22%3A17%3A33Z&sp=r&sv=2023-11-03&sr=b&rscd=inline&rsct=image/png&skoid=6aaadede-4fb3-4698-a8f6-684d7786b067&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2024-07-08T18%3A10%3A20Z&ske=2024-07-09T18%3A10%3A20Z&sks=b&skv=2023-11-03&sig=DmxPnjIjY8LCkTg1lcpcNoyvhBUJVzWwJL4J4jjLIcs%3D"}
14:17:38 started  [sys.download(3)] [input={"location":"cownew.png","url":"https://oaidalleapiprodscus.blob.core.windows.net/private/org-UZ21HIS1j93qUiZVWBOGePHu/user-nfhF7kaasrYgX69n1He52KF9/img-O14wUVsuS2brJ1exDIZp4Rq1.png?st=2024-07-08T20%3A17%3A33Z&se=2024-07-08T22%3A17%3A33Z&sp=r&sv=2023-11-03&sr=b&rscd=inline&rsct=image/png&skoid=6aaadede-4fb3-4698-a8f6-684d7786b067&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2024-07-08T18%3A10%3A20Z&ske=2024-07-09T18%3A10%3A20Z&sks=b&skv=2023-11-03&sig=DmxPnjIjY8LCkTg1lcpcNoyvhBUJVzWwJL4J4jjLIcs%3D"}]
? Description: Downloads a URL, saving the contents to disk at a given location
  Interpreter: sys.download
  Source: Builtin
  Input: {"location":"cownew.png","url":"https://oaidalleapiprodscus.blob.core.windows.net/private/org-UZ21HIS1j93qUiZVWBOGePHu/user-nfhF7kaasrYgX69n1He52KF9/img-O14wUVsuS2brJ1exDIZp4Rq1.png?st=2024-07-08T20%3A17%3A33Z&se=2024-07-08T22%3A17%3A33Z&sp=r&sv=2023-11-03&sr=b&rscd=inline&rsct=image/png&skoid=6aaadede-4fb3-4698-a8f6-684d7786b067&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2024-07-08T18%3A10%3A20Z&ske=2024-07-09T18%3A10%3A20Z&sks=b&skv=2023-11-03&sig=DmxPnjIjY8LCkTg1lcpcNoyvhBUJVzWwJL4J4jjLIcs%3D"}
Allow the above tool to execute? Yes
14:17:40 sent     [sys.download(3)]
14:17:40 ended    [sys.download(3)] [output=file cownew.png already exists and can not be overwritten]
14:17:40 continue [main]
14:17:40 sent     [main]
         content  [1] content | Waiting for model response...
         content  [1] content | <tool call> download -> {"location":"cownew.png","override":"true","url":"https://oaidalleapiprodscus.blob.core.windows.net/private/org-UZ21HIS1j93qUiZVWBOGePHu/user-nfhF7kaasrYgX69n1He52KF9/img-O14wUVsuS2brJ1exDIZp4Rq1.png?st=2024-07-08T20%3A17%3A33Z&se=2024-07-08T22%3A17%3A33Z&sp=r&sv=2023-11-03&sr=b&rscd=inline&rsct=image/png&skoid=6aaadede-4fb3-4698-a8f6-684d7786b067&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2024-07-08T18%3A10%3A20Z&ske=2024-07-09T18%3A10%3A20Z&sks=b&skv=2023-11-03&sig=DmxPnjIjY8LCkTg1lcpcNoyvhBUJVzWwJL4J4jjLIcs%3D"}
14:17:48 started  [sys.download(4)] [input={"location":"cownew.png","override":"true","url":"https://oaidalleapiprodscus.blob.core.windows.net/private/org-UZ21HIS1j93qUiZVWBOGePHu/user-nfhF7kaasrYgX69n1He52KF9/img-O14wUVsuS2brJ1exDIZp4Rq1.png?st=2024-07-08T20%3A17%3A33Z&se=2024-07-08T22%3A17%3A33Z&sp=r&sv=2023-11-03&sr=b&rscd=inline&rsct=image/png&skoid=6aaadede-4fb3-4698-a8f6-684d7786b067&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2024-07-08T18%3A10%3A20Z&ske=2024-07-09T18%3A10%3A20Z&sks=b&skv=2023-11-03&sig=DmxPnjIjY8LCkTg1lcpcNoyvhBUJVzWwJL4J4jjLIcs%3D"}]
? Description: Downloads a URL, saving the contents to disk at a given location
  Interpreter: sys.download
  Source: Builtin
  Input: {"location":"cownew.png","override":"true","url":"https://oaidalleapiprodscus.blob.core.windows.net/private/org-UZ21HIS1j93qUiZVWBOGePHu/user-nfhF7kaasrYgX69n1He52KF9/img-O14wUVsuS2brJ1exDIZp4Rq1.png?st=2024-07-08T20%3A17%3A33Z&se=2024-07-08T22%3A17%3A33Z&sp=r&sv=2023-11-03&sr=b&rscd=inline&rsct=image/png&skoid=6aaadede-4fb3-4698-a8f6-684d7786b067&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2024-07-08T18%3A10%3A20Z&ske=2024-07-09T18%3A10%3A20Z&sks=b&skv=2023-11-03&sig=DmxPnjIjY8LCkTg1lcpcNoyvhBUJVzWwJL4J4jjLIcs%3D"}
Allow the above tool to execute? Yes
14:18:08 sent     [sys.download(4)]
14:18:08 download [https://oaidalleapiprodscus.blob.core.windows.net/private/org-UZ21HIS1j93qUiZVWBOGePHu/user-nfhF7kaasrYgX69n1He52KF9/img-O14wUVsuS2brJ1exDIZp4Rq1.png?rscd=inline&rsct=image%2Fpng&se=2024-07-08T22%3A17%3A33Z&sig=DmxPnjIjY8LCkTg1lcpcNoyvhBUJVzWwJL4J4jjLIcs%3D&ske=2024-07-09T18%3A10%3A20Z&skoid=6aaadede-4fb3-4698-a8f6-684d7786b067&sks=b&skt=2024-07-08T18%3A10%3A20Z&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skv=2023-11-03&sp=r&sr=b&st=2024-07-08T20%3A17%3A33Z&sv=2023-11-03] to [cownew.png]
14:18:09 ended    [sys.download(4)] [output=Downloaded https://oaidalleapiprodscus.blob.core.windows.net/private/org-UZ21HIS1j93qUiZVWBOGePHu/us...]
14:18:09 continue [main]
14:18:09 sent     [main]
         content  [1] content | Waiting for model response...
         content  [1] content | The image has been successfully downloaded and saved as `cownew.png`.
14:18:09 ended    [main] [output=The image has been successfully downloaded and saved as `cownew.png`.]
14:18:09 usage    [total=3851] [prompt=3256] [completion=595]

OUTPUT:

The image has been successfully downloaded and saved as `cownew.png`.
```
