### ISSUE TITLE
Windows - Panic when entering credentials 

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/gptscript#296]
gptscript version v0.0.0-dev-cb54f3b0-dirty

**Steps to reproduce the problem:**
1. Execute gptscript that prompts for credentials - https://github.com/gptscript-ai/search/blob/main/brave/example.gpt
2. When prompted for credentials , enter the token.
This results in `panic: runtime error: invalid memory address or nil pointer dereference` error

```
{
  "completionID": "1",
  "id": "1",
  "level": "debug",
  "logger": "/pkg/monitor",
  "msg": "debug",
  "parentID": "",
  "request": {
    "command": [
      "sys.prompt"
    ],
    "input": "{\"message\": \"Please enter your Brave Search API token.\", \"fields\": \"token\", \"sensitive\": \"true\"}"
  },
  "time": "2024-04-26T21:19:37Z",
  "toolID": "sys.prompt"
}
Please enter your Brave Search API token.
? token {
  "cached": false,
  "completionID": "1",
  "id": "1",
  "level": "debug",
  "logger": "/pkg/monitor",
  "msg": "debug",
  "parentID": "",
  "response": {
    "err": null,
    "output": ""
  },
  "time": "2024-04-26T21:19:46Z",
  "toolID": "sys.prompt"
}
{
  "err": null,
  "level": "debug",
  "logger": "/pkg/monitor",
  "msg": "Run stopped",
  "output": "",
  "runID": "1",
  "time": "2024-04-26T21:19:46Z"
}
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x4f3a70]

goroutine 1 [running]:
github.com/AlecAivazis/survey/v2/terminal.(*RuneReader).ReadLineWithDefault.func2(...)
        C:/Users/sangeetha/go/pkg/mod/github.com/!alec!aivazis/survey/v2@v2.3.7/terminal/runereader.go:65
github.com/AlecAivazis/survey/v2/terminal.(*RuneReader).ReadLineWithDefault(0xc0000aa040, 0x2a, {0xfbfee0, 0x0, 0x0}, {0x0?, 0x0?, 0x0?})
        C:/Users/sangeetha/go/pkg/mod/github.com/!alec!aivazis/survey/v2@v2.3.7/terminal/runereader.go:328 +0xad0
github.com/AlecAivazis/survey/v2/terminal.(*RuneReader).ReadLine(...)
        C:/Users/sangeetha/go/pkg/mod/github.com/!alec!aivazis/survey/v2@v2.3.7/terminal/runereader.go:37
github.com/AlecAivazis/survey/v2.(*Password).Prompt(0xc0001ca8c0, 0xc00017c9e8)
        C:/Users/sangeetha/go/pkg/mod/github.com/!alec!aivazis/survey/v2@v2.3.7/password.go:63 +0x2f9
github.com/AlecAivazis/survey/v2.Ask({0xc00021d330, 0x1, 0x97ffb8?}, {0x7585a0, 0xc0001157b0}, {0xc00021d2f0, 0x1, 0xc00021d258?})
        C:/Users/sangeetha/go/pkg/mod/github.com/!alec!aivazis/survey/v2@v2.3.7/survey.go:366 +0x428
github.com/AlecAivazis/survey/v2.AskOne(...)
        C:/Users/sangeetha/go/pkg/mod/github.com/!alec!aivazis/survey/v2@v2.3.7/survey.go:283
github.com/gptscript-ai/gptscript/pkg/builtin.SysPrompt({0x7a0ce0?, 0xc0001d2b70?}, {0x86b502?, 0x5?, 0xc?}, {0xc000036180, 0x60})
        C:/Users/sangeetha/gptscript/pkg/builtin/builtin.go:783 +0x2f9
github.com/gptscript-ai/gptscript/pkg/engine.(*Engine).runCommand(_, {_, _}, {{{0xc00000a140, 0xa}, {0x87f2c3, 0x1a}, 0x0, {0x78e7d2, 0x13}, ...}, ...}, ...)
        C:/Users/sangeetha/gptscript/pkg/engine/cmd.go:45 +0x35d
github.com/gptscript-ai/gptscript/pkg/engine.(*Engine).Start(_, {{{0xdd6868, 0x1}, {{{...}, {...}, 0x0, {...}, 0x0, 0x0, 0x0, ...}, ...}, ...}, ...}, ...)
        C:/Users/sangeetha/gptscript/pkg/engine/engine.go:192 +0x40c
github.com/gptscript-ai/gptscript/pkg/runner.(*Runner).start(_, {{{0xdd6868, 0x1}, {{{...}, {...}, 0x0, {...}, 0x0, 0x0, 0x0, ...}, ...}, ...}, ...}, ...)
        C:/Users/sangeetha/gptscript/pkg/runner/runner.go:361 +0x7f0
github.com/gptscript-ai/gptscript/pkg/runner.(*Runner).Chat(0xc000132420, {0x98d290, 0xc000078730}, {0x0, 0x0}, {{0xc00000a140, 0xa}, {0xc00000a140, 0xa}, 0xc0001d2210}, ...)
        C:/Users/sangeetha/gptscript/pkg/runner/runner.go:138 +0x589
github.com/gptscript-ai/gptscript/pkg/runner.(*Runner).Run(...)
        C:/Users/sangeetha/gptscript/pkg/runner/runner.go:179
github.com/gptscript-ai/gptscript/pkg/gptscript.(*GPTScript).Run(0xc0001d21e0, {0x98d290, 0xc000078730}, {{0xc00000a140, 0xa}, {0xc00000a140, 0xa}, 0xc0001d2210}, {0xc0001c8e08, 0x31, ...}, ...)
        C:/Users/sangeetha/gptscript/pkg/gptscript/gptscript.go:139 +0x12a
github.com/gptscript-ai/gptscript/pkg/cli.(*GPTScript).Run(0xc00005b500, 0xc0001b0308, {0xc000075d00, 0x2, 0x4})
        C:/Users/sangeetha/gptscript/pkg/cli/gptscript.go:393 +0xc87
github.com/acorn-io/cmd.command.bind.func4(0xc0001b0308, {0xc000075d00, 0x2, 0x4})
        C:/Users/sangeetha/go/pkg/mod/github.com/acorn-io/cmd@v0.0.0-20240404013709-34f690bde37b/builder.go:487 +0x234
github.com/spf13/cobra.(*Command).execute(0xc0001b0308, {0xc00011c010, 0x4, 0x7})
        C:/Users/sangeetha/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:983 +0xaca
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001b0308)
        C:/Users/sangeetha/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        C:/Users/sangeetha/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        C:/Users/sangeetha/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1032
github.com/acorn-io/cmd.Main(0xc0001b0308)
        C:/Users/sangeetha/go/pkg/mod/github.com/acorn-io/cmd@v0.0.0-20240404013709-34f690bde37b/builder.go:74 +0x54
main.main()
        C:/Users/sangeetha/gptscript/main.go:24 +0x9b
Failed to run sys.prompt.
: exit status 1
```

**Comment by g-linville** [comment]
This bug should definitely be gone by now. I've been entering credentials on Windows without any problems.

**Comment by sangee2004** [comment]
This issue is not seen anymore . Able to enter credentials successfully.
