### ISSUE TITLE
 chat: true Internal Server Error when using model anthropic Claude 3

### ISSUE THREAD

**Issue by csantanapr** [gptscript-ai/gptscript#342]
I'm getting an error when trying to any of the anthrophic models

Create tool `pirate.gpt`
```yaml
model: anthropic.claude-3-sonnet-20240229-v1:0 from github.com/gptscript-ai/anthropic-provider
chat: true
Talk like a pirate
```
Run gptscript
```shell
export GPTSCRIPT_DEBUG=true
gtpscript pirate.gpt
```
You get the chat promtpt type `hello captain` and press enter
```
         content  [3] content | Waiting for model response...HTTP REQUEST BODY:  b'{"model":"anthropic.claude-3-sonnet-20240229-v1:0","messages":[{"role":"user","content":"Talk like a pirate"},{"role":"","content":"*in a gruff pirate voice* Ahoy, matey! Avast ye landlubbers! I be Claude, the most fearsome buccaneer to ever sail the seven seas. Shiver me timbers, I\'ll have ye walkin\' the plank if ye don\'t show some respect to the dread pirate captain. Arrr, where be my grog? A pirate\'s thirst be neverendin\'. I\'ve plundered many a treasure from ports near and far. Any scurvy dogs dare cross me path will face the bitter end of me cutlass! Savvy?"},{"role":"user","content":"hello captain"}],"temperature":0,"stream":true}'
here
MESSAGES:  [{'role': 'user', 'content': 'Talk like a pirate'}, {'role': '', 'content': "*in a gruff pirate voice* Ahoy, matey! Avast ye landlubbers! I be Claude, the most fearsome buccaneer to ever sail the seven seas. Shiver me timbers, I'll have ye walkin' the plank if ye don't show some respect to the dread pirate captain. Arrr, where be my grog? A pirate's thirst be neverendin'. I've plundered many a treasure from ports near and far. Any scurvy dogs dare cross me path will face the bitter end of me cutlass! Savvy?"}, {'role': 'user', 'content': 'hello captain'}]
INFO:     127.0.0.1:53115 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/carrlos/Library/Caches/gptscript/repos/runtimes/venv/1bd7aa8f5b5305fd3bfe28755f6a0ead6b2bf5c39a0ea9e527f7d456b3d206e3/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 411, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/carrlos/Library/Caches/gptscript/repos/runtimes/venv/1bd7aa8f5b5305fd3bfe28755f6a0ead6b2bf5c39a0ea9e527f7d456b3d206e3/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/carrlos/Library/Caches/gptscript/repos/runtimes/venv/1bd7aa8f5b5305fd3bfe28755f6a0ead6b2bf5c39a0ea9e527f7d456b3d206e3/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/carrlos/Library/Caches/gptscript/repos/runtimes/venv/1bd7aa8f5b5305fd3bfe28755f6a0ead6b2bf5c39a0ea9e527f7d456b3d206e3/lib/python3.12/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/carrlos/Library/Caches/gptscript/repos/runtimes/venv/1bd7aa8f5b5305fd3bfe28755f6a0ead6b2bf5c39a0ea9e527f7d456b3d206e3/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/Users/carrlos/Library/Caches/gptscript/repos/runtimes/venv/1bd7aa8f5b5305fd3bfe28755f6a0ead6b2bf5c39a0ea9e527f7d456b3d206e3/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/Users/carrlos/Library/Caches/gptscript/repos/runtimes/venv/1bd7aa8f5b5305fd3bfe28755f6a0ead6b2bf5c39a0ea9e527f7d456b3d206e3/lib/python3.12/site-packages/starlette/middleware/base.py", line 189, in __call__
    with collapse_excgroups():
  File "/Users/carrlos/Library/Caches/gptscript/repos/runtimes/python/61f9ec42638d80e92436bdc09bd76431bb84bbdcb603d817fb25fd3775f3e52a/python/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/Users/carrlos/Library/Caches/gptscript/repos/runtimes/venv/1bd7aa8f5b5305fd3bfe28755f6a0ead6b2bf5c39a0ea9e527f7d456b3d206e3/lib/python3.12/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
    raise exc
  File "/Users/carrlos/Library/Caches/gptscript/repos/runtimes/venv/1bd7aa8f5b5305fd3bfe28755f6a0ead6b2bf5c39a0ea9e527f7d456b3d206e3/lib/python3.12/site-packages/starlette/middleware/base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/carrlos/Library/Caches/gptscript/repos/af1982141e037d7960e84964c60e667dd6e057e4/python3.12/main.py", line 22, in log_body
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/carrlos/Library/Caches/gptscript/repos/runtimes/venv/1bd7aa8f5b5305fd3bfe28755f6a0ead6b2bf5c39a0ea9e527f7d456b3d206e3/lib/python3.12/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/Users/carrlos/Library/Caches/gptscript/repos/runtimes/venv/1bd7aa8f5b5305fd3bfe28755f6a0ead6b2bf5c39a0ea9e527f7d456b3d206e3/lib/python3.12/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/carrlos/Library/Caches/gptscript/repos/runtimes/venv/1bd7aa8f5b5305fd3bfe28755f6a0ead6b2bf5c39a0ea9e527f7d456b3d206e3/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/carrlos/Library/Caches/gptscript/repos/runtimes/venv/1bd7aa8f5b5305fd3bfe28755f6a0ead6b2bf5c39a0ea9e527f7d456b3d206e3/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/carrlos/Library/Caches/gptscript/repos/runtimes/venv/1bd7aa8f5b5305fd3bfe28755f6a0ead6b2bf5c39a0ea9e527f7d456b3d206e3/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/carrlos/Library/Caches/gptscript/repos/runtimes/venv/1bd7aa8f5b5305fd3bfe28755f6a0ead6b2bf5c39a0ea9e527f7d456b3d206e3/lib/python3.12/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/carrlos/Library/Caches/gptscript/repos/runtimes/venv/1bd7aa8f5b5305fd3bfe28755f6a0ead6b2bf5c39a0ea9e527f7d456b3d206e3/lib/python3.12/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/Users/carrlos/Library/Caches/gptscript/repos/runtimes/venv/1bd7aa8f5b5305fd3bfe28755f6a0ead6b2bf5c39a0ea9e527f7d456b3d206e3/lib/python3.12/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/Users/carrlos/Library/Caches/gptscript/repos/runtimes/venv/1bd7aa8f5b5305fd3bfe28755f6a0ead6b2bf5c39a0ea9e527f7d456b3d206e3/lib/python3.12/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/carrlos/Library/Caches/gptscript/repos/runtimes/venv/1bd7aa8f5b5305fd3bfe28755f6a0ead6b2bf5c39a0ea9e527f7d456b3d206e3/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/carrlos/Library/Caches/gptscript/repos/runtimes/venv/1bd7aa8f5b5305fd3bfe28755f6a0ead6b2bf5c39a0ea9e527f7d456b3d206e3/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/carrlos/Library/Caches/gptscript/repos/runtimes/venv/1bd7aa8f5b5305fd3bfe28755f6a0ead6b2bf5c39a0ea9e527f7d456b3d206e3/lib/python3.12/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/carrlos/Library/Caches/gptscript/repos/runtimes/venv/1bd7aa8f5b5305fd3bfe28755f6a0ead6b2bf5c39a0ea9e527f7d456b3d206e3/lib/python3.12/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/carrlos/Library/Caches/gptscript/repos/runtimes/venv/1bd7aa8f5b5305fd3bfe28755f6a0ead6b2bf5c39a0ea9e527f7d456b3d206e3/lib/python3.12/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/carrlos/Library/Caches/gptscript/repos/af1982141e037d7960e84964c60e667dd6e057e4/python3.12/main.py", line 117, in completions
    async with client.messages.stream(
  File "/Users/carrlos/Library/Caches/gptscript/repos/runtimes/venv/1bd7aa8f5b5305fd3bfe28755f6a0ead6b2bf5c39a0ea9e527f7d456b3d206e3/lib/python3.12/site-packages/anthropic/lib/streaming/_messages.py", line 396, in __aenter__
    self.__stream = await self.__api_request
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/carrlos/Library/Caches/gptscript/repos/runtimes/venv/1bd7aa8f5b5305fd3bfe28755f6a0ead6b2bf5c39a0ea9e527f7d456b3d206e3/lib/python3.12/site-packages/anthropic/_base_client.py", line 1789, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/carrlos/Library/Caches/gptscript/repos/runtimes/venv/1bd7aa8f5b5305fd3bfe28755f6a0ead6b2bf5c39a0ea9e527f7d456b3d206e3/lib/python3.12/site-packages/anthropic/_base_client.py", line 1492, in request
    return await self._request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/carrlos/Library/Caches/gptscript/repos/runtimes/venv/1bd7aa8f5b5305fd3bfe28755f6a0ead6b2bf5c39a0ea9e527f7d456b3d206e3/lib/python3.12/site-packages/anthropic/_base_client.py", line 1583, in _request
    raise self._make_status_error_from_response(err.response) from None
anthropic.BadRequestError: Error code: 400 - {'message': 'Malformed input request: #: subject must not be valid against schema {"required":["messages"]}#/messages/1/role:  is not a valid enum value, please reformat your input and try again.'}
{
  "err": "error, status code: 500, message: Internal Server Error",
  "level": "debug",
  "logger": "-ai/gptscript/pkg/monitor",
  "msg": "Run stopped",
  "output": "",
  "runID": "3",
  "time": "2024-05-13T22:50:33-04:00"
}
2024/05/13 22:50:33 error, status code: 500, message: Internal Server Error
```

**Comment by drpebcak** [comment]
@csantanapr give this another try for me and see how it works. I believe I have fixed the issue over here: https://github.com/gptscript-ai/anthropic-provider/commit/62cae1defbaf56e79bee96f4659d2b41a55c1506

**Comment by drpebcak** [comment]
Never heard back on this, but we have been using this with chat successfully so I will close this issue.
