### ISSUE TITLE
Windows - image-generation tool fails to load with ImportError for _pydantic_core module

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/gptscript#371]
gptscript version v0.0.0-dev-cb54f3b0-dirty

**Steps to reproduce the problem:**

1. Execute gptscript which uses dalle-image-generation tool
```
Tools: github.com/gptscript-ai/dalle-image-generation

Generate an image of a cow grazing in the open green meadows and return only the url of the image.
```

Script execution fails with following error -
```
ImportError: DLL load failed while importing _pydantic_core: The specified module could not be found.

Debug logs:

.\gptscript.exe --disable-cache examples\image.gpt
17:41:22 started  [main]
17:41:22 sent     [main]
         content  [1] content | Waiting for model response...
         content  [1] content | tool call dalleImageGeneration -> {"prompt":"cow grazing in the open green meadows","quality":"hd"}
17:41:24 started  [credential: github.com/gptscript-ai/dalle-image-generation/credential]
17:41:24 sent     [credential: github.com/gptscript-ai/dalle-image-generation/credential]
17:41:26 ended    [credential: github.com/gptscript-ai/dalle-image-generation/credential] [output={}
]
17:41:26 Not saving empty credential for tool github.com/gptscript-ai/dalle-image-generation/credential
17:41:26 started  [image-generation(3)] [input={"prompt":"cow grazing in the open green meadows","quality":"hd"}]
17:41:26 sent     [image-generation(3)]
Traceback (most recent call last):
  File "C:\Users\sangeetha\AppData\Local\cache\gptscript\repos\a7ce9018b0bbfa4f9b87bf064ba0e97c3d86bd93\python3.12/cli.py", line 4, in <module>
    import openai
  File "C:\Users\sangeetha\AppData\Local\cache\gptscript\repos\runtimes\venv\72aaddfa1021b33db87d57b6245939a9e13250a022ae8028893c4748f47b42e1\Lib\site-packages\openai\__init__.py", line 8, in <module>
    from . import types
  File "C:\Users\sangeetha\AppData\Local\cache\gptscript\repos\runtimes\venv\72aaddfa1021b33db87d57b6245939a9e13250a022ae8028893c4748f47b42e1\Lib\site-packages\openai\types\__init__.py", line 5, in <module>
    from .batch import Batch as Batch
  File "C:\Users\sangeetha\AppData\Local\cache\gptscript\repos\runtimes\venv\72aaddfa1021b33db87d57b6245939a9e13250a022ae8028893c4748f47b42e1\Lib\site-packages\openai\types\batch.py", line 7, in <module>
    from .._models import BaseModel
  File "C:\Users\sangeetha\AppData\Local\cache\gptscript\repos\runtimes\venv\72aaddfa1021b33db87d57b6245939a9e13250a022ae8028893c4748f47b42e1\Lib\site-packages\openai\_models.py", line 22, in <module>
    from pydantic.fields import FieldInfo
  File "C:\Users\sangeetha\AppData\Local\cache\gptscript\repos\runtimes\venv\72aaddfa1021b33db87d57b6245939a9e13250a022ae8028893c4748f47b42e1\Lib\site-packages\pydantic\fields.py", line 16, in <module>
    from pydantic_core import PydanticUndefined
  File "C:\Users\sangeetha\AppData\Local\cache\gptscript\repos\runtimes\venv\72aaddfa1021b33db87d57b6245939a9e13250a022ae8028893c4748f47b42e1\Lib\site-packages\pydantic_core\__init__.py", line 6, in <module>
    from ._pydantic_core import (
ImportError: DLL load failed while importing _pydantic_core: The specified module could not be found.
17:41:27 failed to run tool [image-generation] cmd [C:\Users\sangeetha\AppData\Local\cache\gptscript\repos\runtimes\venv\72aaddfa1021b33db87d57b6245939a9e13250a022ae8028893c4748f47b42e1\Scripts\python3.EXE C:\Users\sangeetha\AppData\Local\cache\gptscript\repos\a7ce9018b0bbfa4f9b87bf064ba0e97c3d86bd93\python3.12/cli.py --prompt=cow grazing in the open green meadows --size= --quality=hd --number=]: exit status 1
2024/04/29 17:41:27 ERROR: Traceback (most recent call last):
  File "C:\Users\sangeetha\AppData\Local\cache\gptscript\repos\a7ce9018b0bbfa4f9b87bf064ba0e97c3d86bd93\python3.12/cli.py", line 4, in <module>
    import openai
  File "C:\Users\sangeetha\AppData\Local\cache\gptscript\repos\runtimes\venv\72aaddfa1021b33db87d57b6245939a9e13250a022ae8028893c4748f47b42e1\Lib\site-packages\openai\__init__.py", line 8, in <module>
    from . import types
  File "C:\Users\sangeetha\AppData\Local\cache\gptscript\repos\runtimes\venv\72aaddfa1021b33db87d57b6245939a9e13250a022ae8028893c4748f47b42e1\Lib\site-packages\openai\types\__init__.py", line 5, in <module>
    from .batch import Batch as Batch
  File "C:\Users\sangeetha\AppData\Local\cache\gptscript\repos\runtimes\venv\72aaddfa1021b33db87d57b6245939a9e13250a022ae8028893c4748f47b42e1\Lib\site-packages\openai\types\batch.py", line 7, in <module>
    from .._models import BaseModel
  File "C:\Users\sangeetha\AppData\Local\cache\gptscript\repos\runtimes\venv\72aaddfa1021b33db87d57b6245939a9e13250a022ae8028893c4748f47b42e1\Lib\site-packages\openai\_models.py", line 22, in <module>
    from pydantic.fields import FieldInfo
  File "C:\Users\sangeetha\AppData\Local\cache\gptscript\repos\runtimes\venv\72aaddfa1021b33db87d57b6245939a9e13250a022ae8028893c4748f47b42e1\Lib\site-packages\pydantic\fields.py", line 16, in <module>
    from pydantic_core import PydanticUndefined
  File "C:\Users\sangeetha\AppData\Local\cache\gptscript\repos\runtimes\venv\72aaddfa1021b33db87d57b6245939a9e13250a022ae8028893c4748f47b42e1\Lib\site-packages\pydantic_core\__init__.py", line 6, in <module>
    from ._pydantic_core import (
ImportError: DLL load failed while importing _pydantic_core: The specified module could not be found.
: exit status 1
```

**Comment by sangee2004** [comment]
We now install ` Microsoft.VCRedist.2015+.x64` as part of installing gptscript using `winget`.

With this present, we are able to use `github.com/gptscript-ai/image-generation` tool successfully to generate images in Windows environment.
