### ISSUE TITLE
Getting a strange error when I run the recipegenerator script. Help?

### ISSUE THREAD

**Issue by reselbob** [gptscript-ai/gptscript#525]
Hi:

I am running Ubuntu 22 LTS

I am trying to run the `recipegenerator.gpt` script. I have one file in the current directory named `grocery.jpg`.

Here are the files in the directory.

```
reselbob@linuxlap:~/Documents/animals$ ls -lh
total 60K
-rw-rw-r-- 1 reselbob reselbob 600 Jun 17 14:07 cat-image-detector.gpt
-rw-rw-r-- 1 reselbob reselbob 21K Jun 20 13:56 fluffy.jpg
-rw-rw-r-- 1 reselbob reselbob 21K Jun 20 14:41 grocery.jpg
-rw-rw-r-- 1 reselbob reselbob 755 Jun 20 12:35 recipegenerator.gpt
-rw-rw-r-- 1 reselbob reselbob 828 Jun 20 14:38 showmecat.gpt
```

Here is the `recipegenerator` script

```
tools: sys.find, sys.read, sys.write, recipegenerator, github.com/gptscript-ai/gpt4-v-vision

Perform the following steps in order:

1. Give me a list of ingredients from the pictures named with grocery in their name located in the current directory and put those extracted ingredients into a list.
2. For each picture analyzed in the previous step, write the ingredients identified into one file name ingredients.md.
3. Based on these ingredients list, suggest me one recipe that is quick to cook and create a new recipe.md file with the recipe

---
name: recipegenerator
description: Generate a recipe from the list of ingredients
args: ingredients: a list of available ingredients.
tools: sys.read

Generate 1 new recipe based on the ingredients list

```

Then I execute the command `gptscript recipegenerator.gpt` I get the following error:

```
14:40:56 started  [main]
14:40:56 sent     [main]
14:40:56 started  [sys.find(2)] [input={"pattern":"*grocery*"}]
14:40:56 sent     [sys.find(2)]
14:40:56 ended    [sys.find(2)] [output=No files found]
14:40:56 continue [main]
14:40:56 sent     [main]
14:40:56 ended    [main] [output=It appears there are no files with \"grocery\" in their name in the current directory. Please ensure t...]

OUTPUT:

It appears there are no files with "grocery" in their name in the current directory. Please ensure the files are correctly named or located in the current directory.
reselbob@linuxlap:~/Documents/animals$ cp fluffy.jpg grocery.jpg
reselbob@linuxlap:~/Documents/animals$ gptscript recipegenerator.gpt 
14:41:33 started  [main]
14:41:33 sent     [main]
14:41:33 started  [sys.find(2)] [input={"pattern":"*grocery*"}]
14:41:33 sent     [sys.find(2)]
14:41:33 ended    [sys.find(2)] [output=grocery.jpg]
14:41:33 continue [main]
14:41:33 sent     [main]
14:41:34 started  [vision(3)] [input={"images":"file:grocery.jpg","prompt":"Extract the list of ingredients from this image"}]
14:41:34 sent     [vision(3)]
node:fs:580
  return binding.open(
                 ^

Error: ENOENT: no such file or directory, open 'ocery.jpg'
    at Object.openSync (node:fs:580:18)
    at Object.readFileSync (node:fs:459:35)
    at resolveImageURL (file:///home/reselbob/.cache/gptscript/repos/7b9869f686ef1ceb30beac258a696b0b03b62e54/tool.gpt/node21/index.js:88:23)
    at Command.run (file:///home/reselbob/.cache/gptscript/repos/7b9869f686ef1ceb30beac258a696b0b03b62e54/tool.gpt/node21/index.js:57:20)
    at Command.listener [as _actionHandler] (/home/reselbob/.cache/gptscript/repos/7b9869f686ef1ceb30beac258a696b0b03b62e54/tool.gpt/node21/node_modules/commander/lib/command.js:482:17)
    at /home/reselbob/.cache/gptscript/repos/7b9869f686ef1ceb30beac258a696b0b03b62e54/tool.gpt/node21/node_modules/commander/lib/command.js:1283:65
    at Command._chainOrCall (/home/reselbob/.cache/gptscript/repos/7b9869f686ef1ceb30beac258a696b0b03b62e54/tool.gpt/node21/node_modules/commander/lib/command.js:1177:12)
    at Command._parseCommand (/home/reselbob/.cache/gptscript/repos/7b9869f686ef1ceb30beac258a696b0b03b62e54/tool.gpt/node21/node_modules/commander/lib/command.js:1283:27)
    at Command.parseAsync (/home/reselbob/.cache/gptscript/repos/7b9869f686ef1ceb30beac258a696b0b03b62e54/tool.gpt/node21/node_modules/commander/lib/command.js:935:16)
    at main (file:///home/reselbob/.cache/gptscript/repos/7b9869f686ef1ceb30beac258a696b0b03b62e54/tool.gpt/node21/index.js:47:17) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'ocery.jpg'
}
```

It's strange that the script is reporting that the file with the that has the characters `grocery` in the file name. It's strange that the characters `gr` are being truncated off of the filename. Help?

**Comment by sangee2004** [comment]
@reselbob `gpt4-v-vision` tool expects the file name parameter to be prepended `file://` but it receives the images parameter with `file:<filename>` format - `[input={"images":"file:grocery.jpg","prompt":"Extract the list of ingredients from this image"}]` which results in the error you are seeing.

Changing the script to include the following additional instruction in step 1 - `When passing filenames to vision tool prepend "file://" to the filenames` should allow for the vision tool to succeed.

```
1. Give me a list of ingredients from the pictures named with grocery in their name located in the current directory and put those extracted ingredients into a list.When passing filenames to vision tool prepend "file://" to the filenames.
```

**Comment by reselbob** [comment]
I did as you instructed @sangee2004 . Now I get the following error output:

```
22:10:56 started  [main]
22:10:56 sent     [main]
22:10:57 started  [sys.find(2)] [input={"pattern":"*grocery*"}]
22:10:57 sent     [sys.find(2)]
22:10:57 ended    [sys.find(2)] [output=grocery.jpg]
22:10:57 continue [main]
22:10:58 sent     [main]
22:10:59 started  [vision(3)] [input={"images":"file://grocery.jpg","prompt":"Extract the list of ingredients from this image."}]
22:10:59 sent     [vision(3)]
file:///home/reselbob/.cache/gptscript/repos/7b9869f686ef1ceb30beac258a696b0b03b62e54/tool.gpt/node21/node_modules/openai/error.mjs:50
            return new NotFoundError(status, error, message, headers);
                   ^

NotFoundError: 404 The model `gpt-4-vision-preview` has been deprecated, learn more here: https://platform.openai.com/docs/deprecations
    at APIError.generate (file:///home/reselbob/.cache/gptscript/repos/7b9869f686ef1ceb30beac258a696b0b03b62e54/tool.gpt/node21/node_modules/openai/error.mjs:50:20)
    at OpenAI.makeStatusError (file:///home/reselbob/.cache/gptscript/repos/7b9869f686ef1ceb30beac258a696b0b03b62e54/tool.gpt/node21/node_modules/openai/core.mjs:268:25)
    at OpenAI.makeRequest (file:///home/reselbob/.cache/gptscript/repos/7b9869f686ef1ceb30beac258a696b0b03b62e54/tool.gpt/node21/node_modules/openai/core.mjs:311:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Command.run (file:///home/reselbob/.cache/gptscript/repos/7b9869f686ef1ceb30beac258a696b0b03b62e54/tool.gpt/node21/index.js:63:20)
    at async Command.parseAsync (/home/reselbob/.cache/gptscript/repos/7b9869f686ef1ceb30beac258a696b0b03b62e54/tool.gpt/node21/node_modules/commander/lib/command.js:935:5)
    at async main (file:///home/reselbob/.cache/gptscript/repos/7b9869f686ef1ceb30beac258a696b0b03b62e54/tool.gpt/node21/index.js:47:3) {
  status: 404,
  headers: {
    'alt-svc': 'h3=":443"; ma=86400',
    'cf-cache-status': 'DYNAMIC',
    'cf-ray': '89717ecc8af12ec6-LAX',
    connection: 'keep-alive',
    'content-encoding': 'gzip',
    'content-type': 'application/json; charset=utf-8',
    date: 'Fri, 21 Jun 2024 05:10:59 GMT',
    server: 'cloudflare',
    'set-cookie': '__cf_bm=t0s7J7xTsPQ1dJn1dwWAFipAsd_46q11mE5Uxi72S8s-1718946659-1.0.1.1-ayqB4P97rMRC4KEKdwfzCz5EG2KvnPjF6DqMNerGiN7e9DbMsUug7IolptHdMfldkynRIfqmFNHwbhSWwNtrtw; path=/; expires=Fri, 21-Jun-24 05:40:59 GMT; domain=.api.openai.com; HttpOnly; Secure; SameSite=None, _cfuvid=KRB5v2FMPVVFhvpQRmJ3V9hXgxgdFGd1f.PAbsZNIMA-1718946659365-0.0.1.1-604800000; path=/; domain=.api.openai.com; HttpOnly; Secure; SameSite=None',
    'strict-transport-security': 'max-age=15724800; includeSubDomains',
    'transfer-encoding': 'chunked',
    vary: 'Origin',
    'x-request-id': 'req_85f2bf4b670d7219d08fabefdc20b739'
  },
  request_id: 'req_85f2bf4b670d7219d08fabefdc20b739',
  error: {
    message: 'The model `gpt-4-vision-preview` has been deprecated, learn more here: https://platform.openai.com/docs/deprecations',
    type: 'invalid_request_error',
    param: null,
    code: 'model_not_found'
  },
  code: 'model_not_found',
  param: null,
  type: 'invalid_request_error'
}

Node.js v21.7.0
22:10:59 ended    [vision(3)] [output=ERROR: got (exit status 1) while running tool, OUTPUT: file:///home/reselbob/.cache/gptscript/repos/...]
22:10:59 continue [main]
22:10:59 sent     [main]
22:11:00 started  [vision(4)] [input={"images":"file://grocery.jpg","prompt":"Extract the list of ingredients from this image.","model":"gpt-4-vision"}]
22:11:00 sent     [vision(4)]
error: option '--model <model>' value 'gpt-4-vision' from env 'MODEL' is invalid. Allowed choices are gpt-4-vision-preview.
22:11:00 ended    [vision(4)] [output=ERROR: got (exit status 1) while running tool, OUTPUT: error: option '--model \u003cmodel\u003e' value 'gpt-4-...]
22:11:00 continue [main]
22:11:00 sent     [main]
22:11:02 started  [vision(5)] [input={"images":"file://grocery.jpg","prompt":"Extract the list of ingredients from this image.","model":"gpt-4-vision-preview-0613"}]
22:11:02 sent     [vision(5)]
error: option '--model <model>' value 'gpt-4-vision-preview-0613' from env 'MODEL' is invalid. Allowed choices are gpt-4-vision-preview.
22:11:02 ended    [vision(5)] [output=ERROR: got (exit status 1) while running tool, OUTPUT: error: option '--model \u003cmodel\u003e' value 'gpt-4-...]
22:11:02 continue [main]
22:11:02 sent     [main]
22:11:04 started  [vision(6)] [input={"images":"file://grocery.jpg","prompt":"Extract the list of ingredients from this image.","model":"gpt-4-vision-preview-0616"}]
22:11:04 sent     [vision(6)]
error: option '--model <model>' value 'gpt-4-vision-preview-0616' from env 'MODEL' is invalid. Allowed choices are gpt-4-vision-preview.
22:11:04 ended    [vision(6)] [output=ERROR: got (exit status 1) while running tool, OUTPUT: error: option '--model \u003cmodel\u003e' value 'gpt-4-...]
22:11:04 continue [main]
22:11:05 sent     [main]
22:11:06 started  [vision(7)] [input={"images":"file://grocery.jpg","prompt":"Extract the list of ingredients from this image.","model":"gpt-4-vision-preview-0614"}]
22:11:06 sent     [vision(7)]
error: option '--model <model>' value 'gpt-4-vision-preview-0614' from env 'MODEL' is invalid. Allowed choices are gpt-4-vision-preview.
22:11:06 ended    [vision(7)] [output=ERROR: got (exit status 1) while running tool, OUTPUT: error: option '--model \u003cmodel\u003e' value 'gpt-4-...]
22:11:06 continue [main]
22:11:06 sent     [main]
22:11:08 ended    [main] [output=It seems that the model required for image analysis is deprecated and not available. Therefore, I am...]
22:11:08 usage    [total=10846] [prompt=10574] [completion=272]

OUTPUT:

It seems that the model required for image analysis is deprecated and not available. Therefore, I am unable to extract the ingredients from the image.

If you have any other instructions or need assistance with something else, please let me know.
```

**Comment by sangee2004** [comment]
With latest version of vision tool , issue relating to handling files as input for `images` parameter as well as using the `gpt-4o` as default model provider is addressed.

**Comment by reselbob** [comment]
Thanks @sangee2004 Tell me please, is there documentation or are there samples?

**Comment by sangee2004** [comment]
@reselbob We have our docs site - https://docs.gptscript.ai/ which outlines some sample chat script workflows in "Examples and Guides" section. There are also example scripts available in https://github.com/gptscript-ai/gptscript/tree/main/examples. 

There are sample scripts that uses tools that can be found under `/examples` folder of the tools github location like https://github.com/gptscript-ai/gpt4-v-vision/tree/main/examples  (for vision tool - github.com/gptscript-ai/gpt4-v-vision) and https://github.com/gptscript-ai/dalle-image-generation/tree/main/examples (for image generation tool - github.com/gptscript-ai/dalle-image-generation).

Please let me know if this is helpful or if you are looking for anything in particular.

**Comment by njhale** [comment]
@reselbob I believe the issues you were encountering in https://github.com/gptscript-ai/gptscript/issues/525#issuecomment-2182013078 should now be resolved with the latest version of `gpt4-v-vision`, which means re-running your script from https://github.com/gptscript-ai/gptscript/issues/525#issuecomment-2182013078 with the `--disable-cache` flag -- (see the docs for more info about tool caching)[https://docs.gptscript.ai/faqs#git-commit-hash-lookups-for-tools] -- should work now without any further changes.

You should also be able to remove the `file://` prefix from the file paths in your tool bodies too.

I'm going to close this out, but if it still doesn't work for you, please feel free to comment and we can reopen.
