### ISSUE TITLE
runtime error seen when trying to delete credentials.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/gptscript#598]
gptscript version v0.9.0+37be71d1

**Steps to reproduce the problem:**
1. Try to delete any existing credential 

This results in `panic: runtime error: invalid memory address or nil pointer dereference` error.
```
gptscript credentials delete sys.openai                                                   
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x28 pc=0x102b79ba0]

goroutine 1 [running]:
github.com/spf13/pflag.(*FlagSet).getFlagType(0x14000434600, {0x14000037fc8, 0x13}, {0x10328621e, 0xb}, 0x1037c9a48)
	github.com/spf13/pflag@v1.0.5/flag.go:381 +0x70
github.com/spf13/pflag.(*FlagSet).GetStringSlice(0x14000037fc8?, {0x14000037fc8?, 0x103618988?})
	github.com/spf13/pflag@v1.0.5/string_slice.go:90 +0x34
github.com/gptscript-ai/cmd.assignSlices(0x1400046b208, 0x102bb9df4?)
	github.com/gptscript-ai/cmd@v0.0.0-20240625175447-4250b42feb7d/builder.go:392 +0xdc
github.com/gptscript-ai/cmd.command.bind.func2(0x1400046b208, {0x14000402a80, 0x1, 0x1})
	github.com/gptscript-ai/cmd@v0.0.0-20240625175447-4250b42feb7d/builder.go:468 +0x100
github.com/spf13/cobra.(*Command).execute(0x1400046b208, {0x140000300b0, 0x1, 0x1})
	github.com/spf13/cobra@v1.8.0/command.go:954 +0x724
github.com/spf13/cobra.(*Command).ExecuteC(0x1400046a308)
	github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.8.0/command.go:1032
github.com/gptscript-ai/cmd.Main(0x1400046a308)
	github.com/gptscript-ai/cmd@v0.0.0-20240625175447-4250b42feb7d/builder.go:78 +0x54
github.com/gptscript-ai/gptscript/pkg/cli.Main()
	github.com/gptscript-ai/gptscript/pkg/cli/main.go:21 +0xec
main.main()
	github.com/gptscript-ai/gptscript/main.go:10 +0x1c
```

**Comment by njhale** [comment]
Fixed by https://github.com/gptscript-ai/gptscript/pull/599

**Comment by sangee2004** [comment]
Tested with gptscript version -`v0.0.0-dev-134dcde9-dirty`
Able to delete credentials. successfully.
