### ISSUE TITLE
UI - "500 Internal Server Error" seen when existing cache repos are deleted.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/gptscript#616]
Server - gptscript version v0.9.2+0f32a9d8

Steps to reproduce the problem:
1. Launch ui - `gptscript --ui`
2. Wait for the UI to launch successfully.
3. Now delete all cache directory from `~/Library/Caches/gptscript`
4. Notice that the UI session gets a  "500 Internal Server Error" and following errors are seen in the console logs:

```
 ⨯ unhandledRejection: Error: ENOENT: no such file or directory, scandir '/Users/sangeethahariharan/Library/Caches/gptscript/repos/776d6d05a205a5c9adb854cd6617d7abc2bca5fd/tool.gpt/node21/app'
    at async Object.readdir (node:internal/fs/promises:949:18)
    at async /Users/sangeethahariharan/Library/Caches/gptscript/repos/776d6d05a205a5c9adb854cd6617d7abc2bca5fd/tool.gpt/node21/node_modules/next/dist/lib/recursive-readdir.js:39:29
    at async Promise.all (index 0)
    at async recursiveReadDir (/Users/sangeethahariharan/Library/Caches/gptscript/repos/776d6d05a205a5c9adb854cd6617d7abc2bca5fd/tool.gpt/node21/node_modules/next/dist/lib/recursive-readdir.js:32:25)
    at async /Users/sangeethahariharan/Library/Caches/gptscript/repos/776d6d05a205a5c9adb854cd6617d7abc2bca5fd/tool.gpt/node21/node_modules/next/dist/server/future/route-matcher-providers/dev/helpers/file-reader/batched-file-reader.js:71:25
    at async Promise.all (index 0)
    at async BatchedFileReader.load (/Users/sangeethahariharan/Library/Caches/gptscript/repos/776d6d05a205a5c9adb854cd6617d7abc2bca5fd/tool.gpt/node21/node_modules/next/dist/server/future/route-matcher-providers/dev/helpers/file-reader/batched-file-reader.js:67:25)
    at async /Users/sangeethahariharan/Library/Caches/gptscript/repos/776d6d05a205a5c9adb854cd6617d7abc2bca5fd/tool.gpt/node21/node_modules/next/dist/server/future/route-matcher-providers/dev/helpers/file-reader/batched-file-reader.js:41:26 {
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: '/Users/sangeethahariharan/Library/Caches/gptscript/repos/776d6d05a205a5c9adb854cd6617d7abc2bca5fd/tool.gpt/node21/app'
```

**Comment by thedadams** [comment]
In this case, gptscript is responsible for creating the cache directory and workspaces. The UI can't recover if the directories have been deleted.

In other words, I believe this is working as expected.

**Comment by cjellick** [comment]
Does it recover when you relaunch? If yes, please close this issue

**Comment by sangee2004** [comment]
It does recover on relaunching UI.
