### ISSUE TITLE
UI - Allowed to enter chat messages  when user has not taken any action on a confirm message from previous chat  resulting thread getting to unresponsive state.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/gptscript#626]
gptscript version - `v0.0.0-dev-0c73f4b8-dirty`

**Steps to reproduce the problem:**

1. Launch UI for remote script -`gptscript --ui --workspace ./newthread --disable-cache github.com/gptscript-ai/cli-demo`

2.  Start a chat message that requires confirmation for tool repo.
3. Do not take any action on the confirmation prompt.
4. Type another chat message and send it (Enter)

This results in no response being received for this message:

<img width="823" alt="Screenshot 2024-07-12 at 1 42 11 PM" src="https://github.com/user-attachments/assets/f0ceef41-d5cf-4ba1-b3c6-e1011c6f22e5">

Following error seen in console:
```
 ⨯ unhandledRejection: Error: Run must in creating, continue or error state, not running
    at Run.nextChat (file:///Users/sangeethahariharan/Library/Caches/gptscript/repos/161cfbb4c63e7d55f8cd41dd6f428b222251be44/tool.gpt/node21/node_modules/@gptscript-ai/gptscript/dist/gptscript.js:234:20)
    at Socket.<anonymous> (file:///Users/sangeethahariharan/Library/Caches/gptscript/repos/161cfbb4c63e7d55f8cd41dd6f428b222251be44/tool.gpt/node21/server.mjs:138:43)
    at Socket.emit (node:events:519:28)
    at Socket.emitUntyped (/Users/sangeethahariharan/Library/Caches/gptscript/repos/161cfbb4c63e7d55f8cd41dd6f428b222251be44/tool.gpt/node21/node_modules/socket.io/dist/typed-events.js:69:22)
    at /Users/sangeethahariharan/Library/Caches/gptscript/repos/161cfbb4c63e7d55f8cd41dd6f428b222251be44/tool.gpt/node21/node_modules/socket.io/dist/socket.js:704:39
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
 ⨯ unhandledRejection: Error: Run must in creating, continue or error state, not running
    at Run.nextChat (file:///Users/sangeethahariharan/Library/Caches/gptscript/repos/161cfbb4c63e7d55f8cd41dd6f428b222251be44/tool.gpt/node21/node_modules/@gptscript-ai/gptscript/dist/gptscript.js:234:20)
    at Socket.<anonymous> (file:///Users/sangeethahariharan/Library/Caches/gptscript/repos/161cfbb4c63e7d55f8cd41dd6f428b222251be44/tool.gpt/node21/server.mjs:138:43)
    at Socket.emit (node:events:519:28)
    at Socket.emitUntyped (/Users/sangeethahariharan/Library/Caches/gptscript/repos/161cfbb4c63e7d55f8cd41dd6f428b222251be44/tool.gpt/node21/node_modules/socket.io/dist/typed-events.js:69:22)
    at /Users/sangeethahariharan/Library/Caches/gptscript/repos/161cfbb4c63e7d55f8cd41dd6f428b222251be44/tool.gpt/node21/node_modules/socket.io/dist/socket.js:704:39
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
```

5. Even if we go back and accept the confirmation prompt for the previous message, it gets stuck in "calling tool.." and we are not able to recover from this state. Further messages sent also end up not being processsed.

  
<img width="749" alt="Screenshot 2024-07-12 at 1 47 22 PM" src="https://github.com/user-attachments/assets/944468ae-c177-498e-8c3f-760f74e8ede6">

**Expected Behavior:**
1. Should not be allowed to enter anther chat message when waiting for confirmation on the previous chat.

**Comment by tylerslaton** [comment]
I see this behavior as fixed. Can you look again @sangee2004 ?
