### ISSUE TITLE
UI - Not able to present google auth errors when chat messages encounter it.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/gptscript#641]
gptscript version - v0.0.0-dev-6e92ee7a-dirty

**Steps to reproduce the problem:**

**Pre Req** - In my case I dont have gcloud authentication setup , so using  github.com/gptscript-ai/gemini-vertexai-provider would fail.

**Steps to reproduce the problem:**

1. Launch UI using gemini vertexai provider for the following script - `DISABLE_CACHE=true gptscript --disable-cache  --default-model 'gemini-1.0-pro from github.com/gptscript-ai/gemini-vertexai-provider' --ui chat_internet.gpt`
```
Tools: github.com/gptscript-ai/answers-from-the-internet, github.com/gptscript-ai/dalle-image-generation
Model: gpt-4o
Chat: true

You are a good assistant. Introduce yourself and wait for the user to ask you a question. Always include source of the search results in the response.
```

2. Ask any question 

Notice that the chat message disappears and nothing happens.

Following errors are seen in console:

```
 ⨯ unhandledRejection: TypeError: Cannot create property 'digest' on string 'error, status code: 500, message: {"detail":"503 Getting metadata from plugin failed with error: Reauthentication is needed. Please run `gcloud auth application-default login` to reauthenticate."}'
    at /Users/sangeethahariharan/Library/Caches/gptscript/repos/de7395ca8d353df9ea3e521a513bfc853feab73e/tool.gpt/node21/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:36:17727
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at eL (/Users/sangeethahariharan/Library/Caches/gptscript/repos/de7395ca8d353df9ea3e521a513bfc853feab73e/tool.gpt/node21/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:273726)
    at /Users/sangeethahariharan/Library/Caches/gptscript/repos/de7395ca8d353df9ea3e521a513bfc853feab73e/tool.gpt/node21/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:269554
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
 ⨯ unhandledRejection: TypeError: Cannot create property 'digest' on string 'error, status code: 500, message: {"detail":"503 Getting metadata from plugin failed with error: Reauthentication is needed. Please run `gcloud auth application-default login` to reauthenticate."}'
    at /Users/sangeethahariharan/Library/Caches/gptscript/repos/de7395ca8d353df9ea3e521a513bfc853feab73e/tool.gpt/node21/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:36:17727
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at eL (/Users/sangeethahariharan/Library/Caches/gptscript/repos/de7395ca8d353df9ea3e521a513bfc853feab73e/tool.gpt/node21/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:273726)
    at /Users/sangeethahariharan/Library/Caches/gptscript/repos/de7395ca8d353df9ea3e521a513bfc853feab73e/tool.gpt/node21/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:269554
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

```
 ⨯ unhandledRejection: TypeError: Cannot create property 'digest' on string 'error, status code: 500, message: {"detail":"503 Getting metadata from plugin failed with error: Reauthentication is needed. Please run `gcloud auth application-default login` to reauthenticate."}'
    at /Users/sangeethahariharan/Library/Caches/gptscript/repos/de7395ca8d353df9ea3e521a513bfc853feab73e/tool.gpt/node21/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:36:17727
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at eL (/Users/sangeethahariharan/Library/Caches/gptscript/repos/de7395ca8d353df9ea3e521a513bfc853feab73e/tool.gpt/node21/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:273726)
    at /Users/sangeethahariharan/Library/Caches/gptscript/repos/de7395ca8d353df9ea3e521a513bfc853feab73e/tool.gpt/node21/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:269554
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
 ⨯ unhandledRejection: TypeError: Cannot create property 'digest' on string 'error, status code: 500, message: {"detail":"503 Getting metadata from plugin failed with error: Reauthentication is needed. Please run `gcloud auth application-default login` to reauthenticate."}'
    at /Users/sangeethahariharan/Library/Caches/gptscript/repos/de7395ca8d353df9ea3e521a513bfc853feab73e/tool.gpt/node21/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:36:17727
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at eL (/Users/sangeethahariharan/Library/Caches/gptscript/repos/de7395ca8d353df9ea3e521a513bfc853feab73e/tool.gpt/node21/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:273726)
    at /Users/sangeethahariharan/Library/Caches/gptscript/repos/de7395ca8d353df9ea3e521a513bfc853feab73e/tool.gpt/node21/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:269554
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

```
 ⨯ unhandledRejection: TypeError: Cannot create property 'digest' on string 'error, status code: 500, message: {"detail":"503 Getting metadata from plugin failed with error: Reauthentication is needed. Please run `gcloud auth application-default login` to reauthenticate."}'
    at /Users/sangeethahariharan/Library/Caches/gptscript/repos/de7395ca8d353df9ea3e521a513bfc853feab73e/tool.gpt/node21/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:36:17727
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at eL (/Users/sangeethahariharan/Library/Caches/gptscript/repos/de7395ca8d353df9ea3e521a513bfc853feab73e/tool.gpt/node21/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:273726)
    at /Users/sangeethahariharan/Library/Caches/gptscript/repos/de7395ca8d353df9ea3e521a513bfc853feab73e/tool.gpt/node21/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:269554
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
 ⨯ unhandledRejection: TypeError: Cannot create property 'digest' on string 'error, status code: 500, message: {"detail":"503 Getting metadata from plugin failed with error: Reauthentication is needed. Please run `gcloud auth application-default login` to reauthenticate."}'
    at /Users/sangeethahariharan/Library/Caches/gptscript/repos/de7395ca8d353df9ea3e521a513bfc853feab73e/tool.gpt/node21/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:36:17727
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at eL (/Users/sangeethahariharan/Library/Caches/gptscript/repos/de7395ca8d353df9ea3e521a513bfc853feab73e/tool.gpt/node21/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:273726)
    at /Users/sangeethahariharan/Library/Caches/gptscript/repos/de7395ca8d353df9ea3e521a513bfc853feab73e/tool.gpt/node21/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:269554
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
 POST /run?file=chat_internet 500 in 60199ms
```

**Comment by tylerslaton** [comment]
@sangee2004 Is this still an issue now that `--ui` is removed?
