### ISSUE TITLE
UI - Not able to present proper error messages when creation of assisstant fails.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/gptscript#722]
gptscript version v0.0.0-dev+b77cd130

**Steps to reproduce the problem:**
1. Create an assistant with a script name without gpt extension.
2. Following error is presented to the user
<img width="834" alt="Screenshot 2024-08-06 at 11 33 50 AM" src="https://github.com/user-attachments/assets/1f213b6f-4a8f-4ead-a2f7-7762e3444dd9">

This is the console error seen:

```
 ⨯ Error: Cannot find module '/Users/sangeethahariharan/Library/Caches/gptscript/repos/977068302804850113e6a3568506f405c7df76db/tool.gpt/node21/.next/server/pages/_error.js'
Require stack:
- /Users/sangeethahariharan/Library/Caches/gptscript/repos/977068302804850113e6a3568506f405c7df76db/tool.gpt/node21/node_modules/next/dist/server/require.js
- /Users/sangeethahariharan/Library/Caches/gptscript/repos/977068302804850113e6a3568506f405c7df76db/tool.gpt/node21/node_modules/next/dist/server/next-server.js
- /Users/sangeethahariharan/Library/Caches/gptscript/repos/977068302804850113e6a3568506f405c7df76db/tool.gpt/node21/node_modules/next/dist/server/next.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1142:15)
    at /Users/sangeethahariharan/Library/Caches/gptscript/repos/977068302804850113e6a3568506f405c7df76db/tool.gpt/node21/node_modules/next/dist/server/require-hook.js:55:36
    at Module._load (node:internal/modules/cjs/loader:983:27)
    at Module.require (node:internal/modules/cjs/loader:1230:19)
    at mod.require (/Users/sangeethahariharan/Library/Caches/gptscript/repos/977068302804850113e6a3568506f405c7df76db/tool.gpt/node21/node_modules/next/dist/server/require-hook.js:65:28)
    at require (node:internal/modules/helpers:179:18)
    at requirePage (/Users/sangeethahariharan/Library/Caches/gptscript/repos/977068302804850113e6a3568506f405c7df76db/tool.gpt/node21/node_modules/next/dist/server/require.js:109:84)
    at /Users/sangeethahariharan/Library/Caches/gptscript/repos/977068302804850113e6a3568506f405c7df76db/tool.gpt/node21/node_modules/next/dist/server/load-components.js:98:84
    at async loadComponentsImpl (/Users/sangeethahariharan/Library/Caches/gptscript/repos/977068302804850113e6a3568506f405c7df76db/tool.gpt/node21/node_modules/next/dist/server/load-components.js:98:26)
    at async NextNodeServer.findPageComponentsImpl (/Users/sangeethahariharan/Library/Caches/gptscript/repos/977068302804850113e6a3568506f405c7df76db/tool.gpt/node21/node_modules/next/dist/server/next-server.js:710:36) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/sangeethahariharan/Library/Caches/gptscript/repos/977068302804850113e6a3568506f405c7df76db/tool.gpt/node21/node_modules/next/dist/server/require.js',
    '/Users/sangeethahariharan/Library/Caches/gptscript/repos/977068302804850113e6a3568506f405c7df76db/tool.gpt/node21/node_modules/next/dist/server/next-server.js',
    '/Users/sangeethahariharan/Library/Caches/gptscript/repos/977068302804850113e6a3568506f405c7df76db/tool.gpt/node21/node_modules/next/dist/server/next.js'
  ]
}

```

The same behavior is also seen when trying to create an assistant with the same script name

```
Error: Unexpected status 500: ERROR: duplicate key value violates unique constraint "idx_owner_slug" (SQLSTATE 23505)
    at h (/Users/sangeethahariharan/Library/Caches/gptscript/repos/977068302804850113e6a3568506f405c7df76db/tool.gpt/node21/.next/server/chunks/3.js:1:10699)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async o (/Users/sangeethahariharan/Library/Caches/gptscript/repos/977068302804850113e6a3568506f405c7df76db/tool.gpt/node21/.next/server/app/page.js:1:10063)
    at async /Users/sangeethahariharan/Library/Caches/gptscript/repos/977068302804850113e6a3568506f405c7df76db/tool.gpt/node21/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:408
    at async rP (/Users/sangeethahariharan/Library/Caches/gptscript/repos/977068302804850113e6a3568506f405c7df76db/tool.gpt/node21/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:15:8043)
    at async r5 (/Users/sangeethahariharan/Library/Caches/gptscript/repos/977068302804850113e6a3568506f405c7df76db/tool.gpt/node21/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:18:1139)
    at async doRender (/Users/sangeethahariharan/Library/Caches/gptscript/repos/977068302804850113e6a3568506f405c7df76db/tool.gpt/node21/node_modules/next/dist/server/base-server.js:1433:30)
    at async cacheEntry.responseCache.get.routeKind (/Users/sangeethahariharan/Library/Caches/gptscript/repos/977068302804850113e6a3568506f405c7df76db/tool.gpt/node21/node_modules/next/dist/server/base-server.js:1594:28)
    at async NextNodeServer.renderToResponseWithComponentsImpl (/Users/sangeethahariharan/Library/Caches/gptscript/repos/977068302804850113e6a3568506f405c7df76db/tool.gpt/node21/node_modules/next/dist/server/base-server.js:1502:28)
    at async NextNodeServer.renderPageComponent (/Users/sangeethahariharan/Library/Caches/gptscript/repos/977068302804850113e6a3568506f405c7df76db/tool.gpt/node21/node_modules/next/dist/server/base-server.js:1919:24) {
  digest: '2632440956'
}
```

**Comment by tylerslaton** [comment]
This page is delete so should be deleted now @sangee2004

**Comment by sangee2004** [comment]
This workflow is not relevant anymore.
