### ISSUE TITLE
UI - Not able to load the script when setting workspace for a thread and restarting it.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/gptscript#723]
gptscript version v0.0.0-dev+160a7334

**Steps to reproduce the problem:**

1. Launch UI - DISABLE_CACHE=true GATEWAY_URL=https://gateway-api.gptscript.ai gptscript --ui --disable-cache
2. Run the following script from Home page
3. Change the workspace and update.
4. This will force the script to be restarted.
5. After this, UI continues to be stuck in the following state
<img width="1281" alt="Screenshot 2024-08-06 at 11 48 38 AM" src="https://github.com/user-attachments/assets/fb26ef2d-da75-4651-ac03-65c777677ba2">

Following errors seen in console:
```
Error: ENOENT: no such file or directory, open '/var/folders/7x/wj1zrf9s5m92pmf8nctz5cs00000gn/T/gptscript-workspace-1082028672/threads/meta.json'
    at async open (node:internal/fs/promises:637:25)
    at async Object.readFile (node:internal/fs/promises:1246:14)
    at async w (/Users/sangeethahariharan/Library/Caches/gptscript/repos/977068302804850113e6a3568506f405c7df76db/tool.gpt/node21/.next/server/chunks/375.js:4:25776)
    at async /Users/sangeethahariharan/Library/Caches/gptscript/repos/977068302804850113e6a3568506f405c7df76db/tool.gpt/node21/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:408
    at async rP (/Users/sangeethahariharan/Library/Caches/gptscript/repos/977068302804850113e6a3568506f405c7df76db/tool.gpt/node21/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:15:8043)
    at async r5 (/Users/sangeethahariharan/Library/Caches/gptscript/repos/977068302804850113e6a3568506f405c7df76db/tool.gpt/node21/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:18:1139)
    at async doRender (/Users/sangeethahariharan/Library/Caches/gptscript/repos/977068302804850113e6a3568506f405c7df76db/tool.gpt/node21/node_modules/next/dist/server/base-server.js:1433:30)
    at async cacheEntry.responseCache.get.routeKind (/Users/sangeethahariharan/Library/Caches/gptscript/repos/977068302804850113e6a3568506f405c7df76db/tool.gpt/node21/node_modules/next/dist/server/base-server.js:1594:28)
    at async NextNodeServer.renderToResponseWithComponentsImpl (/Users/sangeethahariharan/Library/Caches/gptscript/repos/977068302804850113e6a3568506f405c7df76db/tool.gpt/node21/node_modules/next/dist/server/base-server.js:1502:28)
    at async NextNodeServer.renderPageComponent (/Users/sangeethahariharan/Library/Caches/gptscript/repos/977068302804850113e6a3568506f405c7df76db/tool.gpt/node21/node_modules/next/dist/server/base-server.js:1919:24) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/var/folders/7x/wj1zrf9s5m92pmf8nctz5cs00000gn/T/gptscript-workspace-1082028672/threads/meta.json',
  digest: '3737703588'
```

**Comment by sangee2004** [comment]
This issue is not seen any more when testing with latest UI version from `main`
